### get v2
GET http://localhost:5000/api/get-employee-v2?search_query=andro&page=0&limit=10


###
GET http://localhost:5000/api/get-employee-v2?page=0&limit=10


### get all data v2
GET http://localhost:5000/api/get-employee-v2

###
PATCH http://localhost:5000/api/employee/edit/5
Content-Type: application/json 

{
    "nik": "101243",
    "name": "Marshanda",
    "tanggal_masuk": "2024-02-07",
    "pangkat": "B1",
    "jabatan": "Staff",
    "academic_background": "SMA",
    "nomor_telepon": "082233443322"
}



###
POST http://localhost:5000/api/employee/create 
Content-Type: application/json 

{
    "nik": "101242",
    "name": "Andromeda",
    "tanggal_masuk": "2024-02-07",
    "pangkat": "C1",
    "jabatan": "Staff",
    "academic_background": "S1 Hukum",
    "nomor_telepon": "082233445511"
}

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "username": "testuser10@gmail.com",
    "password": "testpassword10"
}


###
DELETE http://localhost:5000/api/employee/delete/101243


